# Generated by Django 3.1.1 on 2020-09-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('text', models.TextField(verbose_name='text')),
                ('commented_at', models.DateField(verbose_name='commented_at')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='id')),
                ('created_by', models.IntegerField(verbose_name='created_by')),
            ],
        ),
    ]
